PROJECT = simple_pool

DEPS = jamdb_sybase octopus

dep_jamdb_sybase = git https://github.com/erlangbureau/jamdb_sybase.git 0.6.0
dep_octopus = git https://github.com/erlangbureau/octopus.git master

include ../../erlang.mk
